# Git sync
dags:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: nfs-client
    accessMode: ReadWriteMany

  gitSync:
    enabled: true
    repo: https://github.com/JosemaPereira/capstone-project-dags
    branch: feature/load_data
    rev: HEAD
    depth: 1
    maxFailures: 0
    subPath: ""


logs:
  persistence:
    enabled: true
    size: 1Gi
    storageClassName: nfs-client